version: '3.1'

services:
  flaskscheduler:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flaskscheduler
    env_file:
      - .env
    volumes:
      - ./:/var/www
    networks:
      flaskscheduler-network:

  nginxscheduler:
    image: nginx:1.13
    container_name: nginxscheduler
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 5555:80
    restart: always
    depends_on:
      - flaskscheduler
    networks:
      - flaskscheduler-network
      
networks:
  flaskscheduler-network:
    external:
      name: custom_serve_network