{
 "title": "UTAC",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Chemical Tin Prediction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "request_prediction_ct3hours{}", "legendFormat": "Chemical Tin" }
   ]
  },
  {
   "title": "Latency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_latency_seconds{endpoint=~\"/predict/ct/hours3|/predict/st/hours3\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Solder Thickness Prediction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "request_prediction_st3hours{}", "legendFormat": "Solder Thickness" }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_count_total{endpoint=~\"/predict/ct/hours3|/predict/st/hours3\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}