global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
#   external_labels:
#     monitor: 'example'
#
# # Alertmanager configuration
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - localhost:9093

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
#rule_files:
#  - 'rules.yml'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  #- job_name: 'node_exporter'
  #  scrape_interval: 15s
  #  static_configs:
  #    - targets: ['host.docker.internal:9100']

  - job_name: 'UTAC'
    scrape_interval: 60s
    static_configs:
      - targets: ['nginx:80']
  
  - job_name: 'ETL'
    scrape_interval: 60s
    static_configs:
      - targets: ['nginxetlscheduler:80']
  
  - job_name: 'TRAINING'
    scrape_interval: 60s
    static_configs:
      - targets: ['nginxscheduler:80']

