version: '3.1'

services:
  flasketlscheduler:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flasketlscheduler
    env_file:
      - .env
    volumes:
      - ./:/var/www
    networks:
      flasketlscheduler-network:
  
  nginxetlscheduler:
    image: nginx:1.13
    container_name: nginxetlscheduler
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 5554:80
    restart: always
    depends_on:
      - flasketlscheduler
    networks:
      - flasketlscheduler-network
      
networks:
  flasketlscheduler-network:
    external:
      name: custom_serve_network

# volumes:
#   # prometheus_data:
#   mongo_data_etlscheduler:
#   mongo_configdb_etlscheduler: